name: Build
on:
 - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: go build -o isabelle
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: isabelle-linux-x64
          path: isabelle